# Generated by Django 6.1.1 on 2026-09-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(help_text="e.g. 'Oct 2024'", max_length=50)),
                ('verification_url', models.URLField(blank=True, max_length=500)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, help_text='Key coursework, honors, or thesis')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_date', models.CharField(help_text="e.g. 'Jan 2023' or '2023-01'", max_length=50)),
                ('end_date', models.CharField(blank=True, help_text="e.g. 'Present' or 'Dec 2024'", max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Responsibilities, achievements, and impact (supports markdown bullet points)')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='experience/logos/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_library/')),
                ('name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.TextField(help_text='Punchy 1-2 sentence description displayed on project cards')),
                ('category', models.CharField(choices=[('UI/UX Design', 'UI/UX Design'), ('Web Development', 'Web Development'), ('Design Systems', 'Design Systems'), ('Mobile App Design', 'Mobile App Design')], default='UI/UX Design', max_length=50)),
                ('tools_used', models.JSONField(default=list, help_text="List of tools/technologies e.g. ['Figma', 'React', 'Tailwind CSS']")),
                ('project_date', models.CharField(blank=True, default='2025', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/')),
                ('live_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('figma_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Alex Morgan', max_length=150)),
                ('title', models.CharField(default='UI/UX Designer & Frontend Developer', max_length=200)),
                ('tagline', models.TextField(default='Crafting delightful digital experiences through thoughtful design systems and pixel-perfect engineering.')),
                ('bio', models.TextField(default='I bridge the gap between design and engineering. With 5+ years of experience designing intuitive interfaces and turning them into performant, accessible web applications, I help startups and tech companies bring ideas to life.')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_url', models.URLField(blank=True, help_text='Direct link to resume (Google Drive, Dropbox, or PDF)', max_length=500, null=True)),
                ('email', models.EmailField(default='alex.morgan.design@example.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+1 (555) 234-5678', max_length=50)),
                ('location', models.CharField(default='San Francisco, CA (Open to Remote)', max_length=150)),
                ('is_available_for_hire', models.BooleanField(default=True)),
                ('github_url', models.URLField(blank=True, default='https://github.com', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com', max_length=500)),
                ('figma_url', models.URLField(blank=True, default='https://figma.com', max_length=500)),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com', max_length=500)),
                ('dribbble_url', models.URLField(blank=True, default='https://dribbble.com', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('UI/UX Design', 'UI/UX Design'), ('Frontend Development', 'Frontend Development'), ('Tools & Workflow', 'Tools & Workflow'), ('Backend & Database', 'Backend & Database')], default='UI/UX Design', max_length=50)),
                ('icon_name', models.CharField(default='Palette', help_text='Lucide icon identifier (e.g. Figma, Layout, Code, Terminal, Database)', max_length=50)),
                ('level_percentage', models.PositiveIntegerField(default=90, help_text='Skill proficiency percentage (1-100)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('overview', 'Project Overview'), ('problem', 'Problem Statement'), ('research', 'User Research'), ('findings', 'Research Findings'), ('personas', 'User Personas'), ('user_journey', 'User Journey & Mapping'), ('information_architecture', 'Information Architecture'), ('user_flow', 'User Flow'), ('wireframes', 'Wireframes & Low-Fi'), ('ui_design', 'UI Design & High-Fi'), ('design_system', 'Design System & Components'), ('prototype', 'Interactive Prototype'), ('solution', 'Final Solution'), ('results', 'Results & Impact'), ('learnings', 'Learnings & Reflections'), ('custom', 'Custom Section')], default='overview', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Detailed markdown or rich narrative for this section')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/case_studies/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_sections', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
